/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefaultLayoutRouteImport } from './routes/_default/_layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/_layout'
import { Route as DefaultLayoutIndexRouteImport } from './routes/_default/_layout/index'
import { Route as DefaultLayoutSignupRouteImport } from './routes/_default/_layout/signup'
import { Route as DefaultLayoutSentraKiDashboardRouteImport } from './routes/_default/_layout/sentra-ki-dashboard'
import { Route as DefaultLayoutLoginRouteImport } from './routes/_default/_layout/login'
import { Route as AuthLayoutDashboardRouteImport } from './routes/_auth/_layout/dashboard'
import { Route as AuthLayoutChangePasswordRouteImport } from './routes/_auth/_layout/change-password'
import { Route as AuthLayoutSentraKiIndexRouteImport } from './routes/_auth/_layout/sentra-ki/index'
import { Route as AuthLayoutPksIndexRouteImport } from './routes/_auth/_layout/pks/index'
import { Route as AuthLayoutMasterDataUserRouteImport } from './routes/_auth/_layout/master-data/user'
import { Route as AuthLayoutMasterDataInstansiRouteImport } from './routes/_auth/_layout/master-data/instansi'
import { Route as AuthLayoutAdminSentraPermohonanKiRouteImport } from './routes/_auth/_layout/admin-sentra/permohonan-ki'
import { Route as AuthLayoutAdminSentraInformasiKiRouteImport } from './routes/_auth/_layout/admin-sentra/informasi-ki'
import { Route as AuthLayoutAdminSentraDaftarKiRouteImport } from './routes/_auth/_layout/admin-sentra/daftar-ki'

const DefaultLayoutRoute = DefaultLayoutRouteImport.update({
  id: '/_default/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutIndexRoute = DefaultLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutSignupRoute = DefaultLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutSentraKiDashboardRoute =
  DefaultLayoutSentraKiDashboardRouteImport.update({
    id: '/sentra-ki-dashboard',
    path: '/sentra-ki-dashboard',
    getParentRoute: () => DefaultLayoutRoute,
  } as any)
const DefaultLayoutLoginRoute = DefaultLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const AuthLayoutDashboardRoute = AuthLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutChangePasswordRoute =
  AuthLayoutChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutSentraKiIndexRoute = AuthLayoutSentraKiIndexRouteImport.update({
  id: '/sentra-ki/',
  path: '/sentra-ki/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutPksIndexRoute = AuthLayoutPksIndexRouteImport.update({
  id: '/pks/',
  path: '/pks/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutMasterDataUserRoute =
  AuthLayoutMasterDataUserRouteImport.update({
    id: '/master-data/user',
    path: '/master-data/user',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutMasterDataInstansiRoute =
  AuthLayoutMasterDataInstansiRouteImport.update({
    id: '/master-data/instansi',
    path: '/master-data/instansi',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminSentraPermohonanKiRoute =
  AuthLayoutAdminSentraPermohonanKiRouteImport.update({
    id: '/admin-sentra/permohonan-ki',
    path: '/admin-sentra/permohonan-ki',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminSentraInformasiKiRoute =
  AuthLayoutAdminSentraInformasiKiRouteImport.update({
    id: '/admin-sentra/informasi-ki',
    path: '/admin-sentra/informasi-ki',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminSentraDaftarKiRoute =
  AuthLayoutAdminSentraDaftarKiRouteImport.update({
    id: '/admin-sentra/daftar-ki',
    path: '/admin-sentra/daftar-ki',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/change-password': typeof AuthLayoutChangePasswordRoute
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/login': typeof DefaultLayoutLoginRoute
  '/sentra-ki-dashboard': typeof DefaultLayoutSentraKiDashboardRoute
  '/signup': typeof DefaultLayoutSignupRoute
  '/': typeof DefaultLayoutIndexRoute
  '/admin-sentra/daftar-ki': typeof AuthLayoutAdminSentraDaftarKiRoute
  '/admin-sentra/informasi-ki': typeof AuthLayoutAdminSentraInformasiKiRoute
  '/admin-sentra/permohonan-ki': typeof AuthLayoutAdminSentraPermohonanKiRoute
  '/master-data/instansi': typeof AuthLayoutMasterDataInstansiRoute
  '/master-data/user': typeof AuthLayoutMasterDataUserRoute
  '/pks': typeof AuthLayoutPksIndexRoute
  '/sentra-ki': typeof AuthLayoutSentraKiIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof AuthLayoutChangePasswordRoute
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/login': typeof DefaultLayoutLoginRoute
  '/sentra-ki-dashboard': typeof DefaultLayoutSentraKiDashboardRoute
  '/signup': typeof DefaultLayoutSignupRoute
  '/': typeof DefaultLayoutIndexRoute
  '/admin-sentra/daftar-ki': typeof AuthLayoutAdminSentraDaftarKiRoute
  '/admin-sentra/informasi-ki': typeof AuthLayoutAdminSentraInformasiKiRoute
  '/admin-sentra/permohonan-ki': typeof AuthLayoutAdminSentraPermohonanKiRoute
  '/master-data/instansi': typeof AuthLayoutMasterDataInstansiRoute
  '/master-data/user': typeof AuthLayoutMasterDataUserRoute
  '/pks': typeof AuthLayoutPksIndexRoute
  '/sentra-ki': typeof AuthLayoutSentraKiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_default/_layout': typeof DefaultLayoutRouteWithChildren
  '/_auth/_layout/change-password': typeof AuthLayoutChangePasswordRoute
  '/_auth/_layout/dashboard': typeof AuthLayoutDashboardRoute
  '/_default/_layout/login': typeof DefaultLayoutLoginRoute
  '/_default/_layout/sentra-ki-dashboard': typeof DefaultLayoutSentraKiDashboardRoute
  '/_default/_layout/signup': typeof DefaultLayoutSignupRoute
  '/_default/_layout/': typeof DefaultLayoutIndexRoute
  '/_auth/_layout/admin-sentra/daftar-ki': typeof AuthLayoutAdminSentraDaftarKiRoute
  '/_auth/_layout/admin-sentra/informasi-ki': typeof AuthLayoutAdminSentraInformasiKiRoute
  '/_auth/_layout/admin-sentra/permohonan-ki': typeof AuthLayoutAdminSentraPermohonanKiRoute
  '/_auth/_layout/master-data/instansi': typeof AuthLayoutMasterDataInstansiRoute
  '/_auth/_layout/master-data/user': typeof AuthLayoutMasterDataUserRoute
  '/_auth/_layout/pks/': typeof AuthLayoutPksIndexRoute
  '/_auth/_layout/sentra-ki/': typeof AuthLayoutSentraKiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/sentra-ki-dashboard'
    | '/signup'
    | '/'
    | '/admin-sentra/daftar-ki'
    | '/admin-sentra/informasi-ki'
    | '/admin-sentra/permohonan-ki'
    | '/master-data/instansi'
    | '/master-data/user'
    | '/pks'
    | '/sentra-ki'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/sentra-ki-dashboard'
    | '/signup'
    | '/'
    | '/admin-sentra/daftar-ki'
    | '/admin-sentra/informasi-ki'
    | '/admin-sentra/permohonan-ki'
    | '/master-data/instansi'
    | '/master-data/user'
    | '/pks'
    | '/sentra-ki'
  id:
    | '__root__'
    | '/_auth/_layout'
    | '/_default/_layout'
    | '/_auth/_layout/change-password'
    | '/_auth/_layout/dashboard'
    | '/_default/_layout/login'
    | '/_default/_layout/sentra-ki-dashboard'
    | '/_default/_layout/signup'
    | '/_default/_layout/'
    | '/_auth/_layout/admin-sentra/daftar-ki'
    | '/_auth/_layout/admin-sentra/informasi-ki'
    | '/_auth/_layout/admin-sentra/permohonan-ki'
    | '/_auth/_layout/master-data/instansi'
    | '/_auth/_layout/master-data/user'
    | '/_auth/_layout/pks/'
    | '/_auth/_layout/sentra-ki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DefaultLayoutRoute: typeof DefaultLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default/_layout': {
      id: '/_default/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DefaultLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/_layout/': {
      id: '/_default/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutIndexRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_default/_layout/signup': {
      id: '/_default/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof DefaultLayoutSignupRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_default/_layout/sentra-ki-dashboard': {
      id: '/_default/_layout/sentra-ki-dashboard'
      path: '/sentra-ki-dashboard'
      fullPath: '/sentra-ki-dashboard'
      preLoaderRoute: typeof DefaultLayoutSentraKiDashboardRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_default/_layout/login': {
      id: '/_default/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof DefaultLayoutLoginRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_auth/_layout/dashboard': {
      id: '/_auth/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthLayoutDashboardRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/change-password': {
      id: '/_auth/_layout/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthLayoutChangePasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/sentra-ki/': {
      id: '/_auth/_layout/sentra-ki/'
      path: '/sentra-ki'
      fullPath: '/sentra-ki'
      preLoaderRoute: typeof AuthLayoutSentraKiIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/pks/': {
      id: '/_auth/_layout/pks/'
      path: '/pks'
      fullPath: '/pks'
      preLoaderRoute: typeof AuthLayoutPksIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/master-data/user': {
      id: '/_auth/_layout/master-data/user'
      path: '/master-data/user'
      fullPath: '/master-data/user'
      preLoaderRoute: typeof AuthLayoutMasterDataUserRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/master-data/instansi': {
      id: '/_auth/_layout/master-data/instansi'
      path: '/master-data/instansi'
      fullPath: '/master-data/instansi'
      preLoaderRoute: typeof AuthLayoutMasterDataInstansiRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin-sentra/permohonan-ki': {
      id: '/_auth/_layout/admin-sentra/permohonan-ki'
      path: '/admin-sentra/permohonan-ki'
      fullPath: '/admin-sentra/permohonan-ki'
      preLoaderRoute: typeof AuthLayoutAdminSentraPermohonanKiRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin-sentra/informasi-ki': {
      id: '/_auth/_layout/admin-sentra/informasi-ki'
      path: '/admin-sentra/informasi-ki'
      fullPath: '/admin-sentra/informasi-ki'
      preLoaderRoute: typeof AuthLayoutAdminSentraInformasiKiRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin-sentra/daftar-ki': {
      id: '/_auth/_layout/admin-sentra/daftar-ki'
      path: '/admin-sentra/daftar-ki'
      fullPath: '/admin-sentra/daftar-ki'
      preLoaderRoute: typeof AuthLayoutAdminSentraDaftarKiRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutChangePasswordRoute: typeof AuthLayoutChangePasswordRoute
  AuthLayoutDashboardRoute: typeof AuthLayoutDashboardRoute
  AuthLayoutAdminSentraDaftarKiRoute: typeof AuthLayoutAdminSentraDaftarKiRoute
  AuthLayoutAdminSentraInformasiKiRoute: typeof AuthLayoutAdminSentraInformasiKiRoute
  AuthLayoutAdminSentraPermohonanKiRoute: typeof AuthLayoutAdminSentraPermohonanKiRoute
  AuthLayoutMasterDataInstansiRoute: typeof AuthLayoutMasterDataInstansiRoute
  AuthLayoutMasterDataUserRoute: typeof AuthLayoutMasterDataUserRoute
  AuthLayoutPksIndexRoute: typeof AuthLayoutPksIndexRoute
  AuthLayoutSentraKiIndexRoute: typeof AuthLayoutSentraKiIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutChangePasswordRoute: AuthLayoutChangePasswordRoute,
  AuthLayoutDashboardRoute: AuthLayoutDashboardRoute,
  AuthLayoutAdminSentraDaftarKiRoute: AuthLayoutAdminSentraDaftarKiRoute,
  AuthLayoutAdminSentraInformasiKiRoute: AuthLayoutAdminSentraInformasiKiRoute,
  AuthLayoutAdminSentraPermohonanKiRoute:
    AuthLayoutAdminSentraPermohonanKiRoute,
  AuthLayoutMasterDataInstansiRoute: AuthLayoutMasterDataInstansiRoute,
  AuthLayoutMasterDataUserRoute: AuthLayoutMasterDataUserRoute,
  AuthLayoutPksIndexRoute: AuthLayoutPksIndexRoute,
  AuthLayoutSentraKiIndexRoute: AuthLayoutSentraKiIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DefaultLayoutRouteChildren {
  DefaultLayoutLoginRoute: typeof DefaultLayoutLoginRoute
  DefaultLayoutSentraKiDashboardRoute: typeof DefaultLayoutSentraKiDashboardRoute
  DefaultLayoutSignupRoute: typeof DefaultLayoutSignupRoute
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute
}

const DefaultLayoutRouteChildren: DefaultLayoutRouteChildren = {
  DefaultLayoutLoginRoute: DefaultLayoutLoginRoute,
  DefaultLayoutSentraKiDashboardRoute: DefaultLayoutSentraKiDashboardRoute,
  DefaultLayoutSignupRoute: DefaultLayoutSignupRoute,
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
}

const DefaultLayoutRouteWithChildren = DefaultLayoutRoute._addFileChildren(
  DefaultLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DefaultLayoutRoute: DefaultLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
